export default {
  FADE: 'uk-animation-fade',
  SCALE_UP: 'uk-animation-scale-up',
  SCALE_DOWN: 'uk-animation-scale-down',
  SLIDE_TOP: 'uk-animation-slide-top',
  SLIDE_BOTTOM: 'uk-animation-slide-bottom',
  SLIDE_LEFT: 'uk-animation-slide-left',
  SLIDE_RIGHT: 'uk-animation-slide-right',
  SLIDE_TOP_SMALL: 'uk-animation-slide-top-small',
  SLIDE_BOTTOM_SMALL: 'uk-animation-slide-bottom-small',
  SLIDE_LEFT_SMALL: 'uk-animation-slide-left-small',
  SLIDE_RIGHT_SMALL: 'uk-animation-slide-right-small',
  SLIDE_TOP_MEDIUM: 'uk-animation-slide-top-medium',
  SLIDE_BOTTOM_MEDIUM: 'uk-animation-slide-bottom-medium',
  SLIDE_LEFT_MEDIUM: 'uk-animation-slide-left-medium',
  SLIDE_RIGHT_MEDIUM: 'uk-animation-slide-right-medium',
  KENBURNS: 'uk-animation-kenburns',
  SHAKE: 'uk-animation-shake',
};
